meta_product_name: "Megalithipedia"
meta_title: "Megalithipedia - Find Ancient Megaliths and Archeological Sites Near You"
meta_description: "Megalithipedia is home to a growing community of historical enthusiasts. Discover hidden sites, plan excursions, connect with megalith experts and more, at Megalithipedia."
meta_image: "logo.png"
