meta_product_name: "Megalithipedia"
meta_title: "Megalithipedia - Find Ancient Megaliths and Archeological Sites Near You"
meta_description: "Megalithipedia is home to a growing "
meta_image: "logo.png" # should exist in `app/assets/images/`
